name: project3-compose

# note for noobs like me: top-level keys starting with `x-` are ignored by docker compose, so we can put our shared configs here
x-all-nodes-shared-config: &shared-config
  # volumes:
  #   - type: bind
  #     source: ./.uv_cache # TODO?: point to host system's global uv cache? this would be for container run time
  #     target: /root/.cache/uv
  # environment:
  #   - UV_CACHE_DIR=/root/.cache/uv
  build:
    context: ..
    dockerfile: docker/Dockerfile
  networks:
    - project3-net
  working_dir: /app
  # image: project3-image:latest # just label for the container; doesn't exist in any registry
  pull_policy: never # thus don't pull

# x-service-nodes-shared-config: &service-config
#   command: ["python", "-u", "service_node/service_node.py"]
#   profiles: [server]

# x-replica-nodes-config: &replica-config
#   networks:
#     - project3-net
#   working_dir: /app
#   image: project3-replica-image:latest # just label for the container; doesn't exist in any registry
#   pull_policy: never # thus don't pull

#   build:
#     context: ..
#     dockerfile: replica_node/Dockerfile
#   command: ["python", "-u", "replica_node/replica_node.py"]
#   profiles: [server]

x-client-nodes-config: &client-config
  build:
    context: ..
    dockerfile: docker/Dockerfile
  networks:
    - project3-net
  working_dir: /app
  image: project3-client-image:latest
  pull_policy: never
  command: ["python", "-u", "client/client.py", "create-item", "1", "2", "3", "4", "5", "6"]
  profiles: [client]

services:
  controller:
    <<: *shared-config # copy in contents of the shared config
    container_name: p3-controller
    hostname: controller
    environment:
      PORT: 50050

    volumes:
      # mount docker socket so controller can spin up containers
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["python", "-u", "controller/controller.py"]
    image: project3-controller-image:latest
    profiles: [server]

  service-node-template:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - project3-net
    working_dir: /app
    image: project3-service-node-image:latest # just label for the container; doesn't exist in any registry
    pull_policy: never # thus don't pull
    profiles: [template]
    command: ["python", "-u", "service_node/service_node.py"]

  replica-node-template:
    build:
      context: ..
      dockerfile: replica_node/Dockerfile
    networks:
      - project3-net
    working_dir: /app
    image: project3-replica-node-image:latest
    pull_policy: never
    profiles: [template]
    command: ["python", "-u", "replica_node/replica_node.py"]

  # service-node-0:
  #   <<: [*shared-config, *service-config] # note for yaml noobs like me: this is how you include keys from two or more referenced maps
  #   container_name: p3-service-node-0
  #   hostname: service-node-0
  #   environment:
  #     PORT: 50150
  # # service-node-1:
  # #   <<: [*shared-config, *service-config]
  # #   container_name: p3-service-node-1
  # #   hostname: service-node-1
  # # service-node-2:
  # #   <<: [*shared-config, *service-config]
  # #   container_name: p3-service-node-2
  # #   hostname: service-node-2

  # replica-node-0:
  #   <<: *replica-config
  #   container_name: p3-replica-node-0
  #   hostname: replica-node-0
  #   environment:
  #     PORT: 50250

  client-node-0:
    <<: *client-config
    container_name: p3-client-node-0
    hostname: client-node-0
    environment:
      PORT: 50350

networks:
  project3-net: # if rename this, update utils/config.py accordingly
    name: project3-net
    driver: bridge # (default)