# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\x12\x02kv\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"&\n\x0bPutResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03pod\x18\x02 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"8\n\x0bGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0b\n\x03pod\x18\x03 \x01(\t2a\n\x0f\x46rontendService\x12&\n\x03Put\x12\x0e.kv.PutRequest\x1a\x0f.kv.PutResponse\x12&\n\x03Get\x12\x0e.kv.GetRequest\x1a\x0f.kv.GetResponse2`\n\x0eStorageService\x12&\n\x03Put\x12\x0e.kv.PutRequest\x1a\x0f.kv.PutResponse\x12&\n\x03Get\x12\x0e.kv.GetRequest\x1a\x0f.kv.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUTREQUEST']._serialized_start=16
  _globals['_PUTREQUEST']._serialized_end=56
  _globals['_PUTRESPONSE']._serialized_start=58
  _globals['_PUTRESPONSE']._serialized_end=96
  _globals['_GETREQUEST']._serialized_start=98
  _globals['_GETREQUEST']._serialized_end=123
  _globals['_GETRESPONSE']._serialized_start=125
  _globals['_GETRESPONSE']._serialized_end=181
  _globals['_FRONTENDSERVICE']._serialized_start=183
  _globals['_FRONTENDSERVICE']._serialized_end=280
  _globals['_STORAGESERVICE']._serialized_start=282
  _globals['_STORAGESERVICE']._serialized_end=378
# @@protoc_insertion_point(module_scope)
