# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import project3_pb2 as project3__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in project3_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.C_CreateItem = channel.unary_unary(
                '/project3.ControllerService/C_CreateItem',
                request_serializer=project3__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.C_GetItem = channel.unary_unary(
                '/project3.ControllerService/C_GetItem',
                request_serializer=project3__pb2.GetItemRequest.SerializeToString,
                response_deserializer=project3__pb2.GetItemResponse.FromString,
                _registered_method=True)


class ControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def C_CreateItem(self, request, context):
        """TODO: populate messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def C_GetItem(self, request, context):
        """rpc C_SearchItems(google.protobuf.Empty) returns (google.protobuf.Empty);
        rpc C_UpdateItem(google.protobuf.Empty) returns (google.protobuf.Empty);
        rpc C_JoinAuction(google.protobuf.Empty) returns (google.protobuf.Empty);
        rpc C_PlaceBid(google.protobuf.Empty) returns (google.protobuf.Empty);
        rpc C_CheckHealth(google.protobuf.Empty) returns (google.protobuf.Empty);
        rpc C_SendHeartbeat(Heartbeat) returns (google.protobuf.Empty); // (how callee sends a heartbeat message to the controller)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'C_CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.C_CreateItem,
                    request_deserializer=project3__pb2.CreateItemRequest.FromString,
                    response_serializer=project3__pb2.CreateItemResponse.SerializeToString,
            ),
            'C_GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.C_GetItem,
                    request_deserializer=project3__pb2.GetItemRequest.FromString,
                    response_serializer=project3__pb2.GetItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project3.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project3.ControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def C_CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ControllerService/C_CreateItem',
            project3__pb2.CreateItemRequest.SerializeToString,
            project3__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def C_GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ControllerService/C_GetItem',
            project3__pb2.GetItemRequest.SerializeToString,
            project3__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServiceNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.S_CreateItem = channel.unary_unary(
                '/project3.ServiceNodeService/S_CreateItem',
                request_serializer=project3__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.S_GetItem = channel.unary_unary(
                '/project3.ServiceNodeService/S_GetItem',
                request_serializer=project3__pb2.GetItemRequest.SerializeToString,
                response_deserializer=project3__pb2.GetItemResponse.FromString,
                _registered_method=True)


class ServiceNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def S_CreateItem(self, request, context):
        """TODO: populate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S_GetItem(self, request, context):
        """rpc S_SearchItems(google.protobuf.Empty) returns (google.protobuf.Empty);
        rpc S_UpdateItem(google.protobuf.Empty) returns (google.protobuf.Empty);
        rpc S_JoinAuction(google.protobuf.Empty) returns (google.protobuf.Empty);
        rpc S_PlaceBid(google.protobuf.Empty) returns (google.protobuf.Empty);
        rpc S_HeartbeatRequest(google.protobuf.Empty) returns (Heartbeat);
        rpc S_Shutdown(google.protobuf.Empty) returns (google.protobuf.Empty); // for later: called by controller to shut down idle node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'S_CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.S_CreateItem,
                    request_deserializer=project3__pb2.CreateItemRequest.FromString,
                    response_serializer=project3__pb2.CreateItemResponse.SerializeToString,
            ),
            'S_GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.S_GetItem,
                    request_deserializer=project3__pb2.GetItemRequest.FromString,
                    response_serializer=project3__pb2.GetItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project3.ServiceNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project3.ServiceNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def S_CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ServiceNodeService/S_CreateItem',
            project3__pb2.CreateItemRequest.SerializeToString,
            project3__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def S_GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ServiceNodeService/S_GetItem',
            project3__pb2.GetItemRequest.SerializeToString,
            project3__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplicaNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.R_CreateItem = channel.unary_unary(
                '/project3.ReplicaNodeService/R_CreateItem',
                request_serializer=project3__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.R_Read = channel.unary_unary(
                '/project3.ReplicaNodeService/R_Read',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.R_Write = channel.unary_unary(
                '/project3.ReplicaNodeService/R_Write',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=project3__pb2.Item.FromString,
                _registered_method=True)


class ReplicaNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def R_CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def R_Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def R_Write(self, request, context):
        """rpc R_HeartbeatRequest(google.protobuf.Empty) returns (Heartbeat);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'R_CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.R_CreateItem,
                    request_deserializer=project3__pb2.CreateItemRequest.FromString,
                    response_serializer=project3__pb2.CreateItemResponse.SerializeToString,
            ),
            'R_Read': grpc.unary_unary_rpc_method_handler(
                    servicer.R_Read,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'R_Write': grpc.unary_unary_rpc_method_handler(
                    servicer.R_Write,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=project3__pb2.Item.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project3.ReplicaNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project3.ReplicaNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicaNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def R_CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ReplicaNodeService/R_CreateItem',
            project3__pb2.CreateItemRequest.SerializeToString,
            project3__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def R_Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ReplicaNodeService/R_Read',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def R_Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ReplicaNodeService/R_Write',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            project3__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
