# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import project3_pb2 as project3__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in project3_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrontendServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateItem = channel.unary_unary(
                '/project3.FrontendService/CreateItem',
                request_serializer=project3__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/project3.FrontendService/GetItem',
                request_serializer=project3__pb2.GetItemRequest.SerializeToString,
                response_deserializer=project3__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/project3.FrontendService/SearchItems',
                request_serializer=project3__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=project3__pb2.SearchItemsResponse.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/project3.FrontendService/UpdateItem',
                request_serializer=project3__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.UpdateItemResponse.FromString,
                _registered_method=True)
        self.PlaceBid = channel.unary_unary(
                '/project3.FrontendService/PlaceBid',
                request_serializer=project3__pb2.PlaceBidRequest.SerializeToString,
                response_deserializer=project3__pb2.PlaceBidResponse.FromString,
                _registered_method=True)
        self.JoinAuction = channel.unary_stream(
                '/project3.FrontendService/JoinAuction',
                request_serializer=project3__pb2.JoinAuctionRequest.SerializeToString,
                response_deserializer=project3__pb2.AuctionUpdate.FromString,
                _registered_method=True)


class FrontendServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinAuction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrontendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=project3__pb2.CreateItemRequest.FromString,
                    response_serializer=project3__pb2.CreateItemResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=project3__pb2.GetItemRequest.FromString,
                    response_serializer=project3__pb2.GetItemResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=project3__pb2.SearchItemsRequest.FromString,
                    response_serializer=project3__pb2.SearchItemsResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=project3__pb2.UpdateItemRequest.FromString,
                    response_serializer=project3__pb2.UpdateItemResponse.SerializeToString,
            ),
            'PlaceBid': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBid,
                    request_deserializer=project3__pb2.PlaceBidRequest.FromString,
                    response_serializer=project3__pb2.PlaceBidResponse.SerializeToString,
            ),
            'JoinAuction': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinAuction,
                    request_deserializer=project3__pb2.JoinAuctionRequest.FromString,
                    response_serializer=project3__pb2.AuctionUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project3.FrontendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project3.FrontendService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrontendService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.FrontendService/CreateItem',
            project3__pb2.CreateItemRequest.SerializeToString,
            project3__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.FrontendService/GetItem',
            project3__pb2.GetItemRequest.SerializeToString,
            project3__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.FrontendService/SearchItems',
            project3__pb2.SearchItemsRequest.SerializeToString,
            project3__pb2.SearchItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.FrontendService/UpdateItem',
            project3__pb2.UpdateItemRequest.SerializeToString,
            project3__pb2.UpdateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.FrontendService/PlaceBid',
            project3__pb2.PlaceBidRequest.SerializeToString,
            project3__pb2.PlaceBidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/project3.FrontendService/JoinAuction',
            project3__pb2.JoinAuctionRequest.SerializeToString,
            project3__pb2.AuctionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.C_CreateItem = channel.unary_unary(
                '/project3.ControllerService/C_CreateItem',
                request_serializer=project3__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.C_GetItem = channel.unary_unary(
                '/project3.ControllerService/C_GetItem',
                request_serializer=project3__pb2.GetItemRequest.SerializeToString,
                response_deserializer=project3__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.C_SearchItems = channel.unary_unary(
                '/project3.ControllerService/C_SearchItems',
                request_serializer=project3__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=project3__pb2.SearchItemsResponse.FromString,
                _registered_method=True)
        self.C_UpdateItem = channel.unary_unary(
                '/project3.ControllerService/C_UpdateItem',
                request_serializer=project3__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.UpdateItemResponse.FromString,
                _registered_method=True)
        self.C_JoinAuction = channel.unary_stream(
                '/project3.ControllerService/C_JoinAuction',
                request_serializer=project3__pb2.JoinAuctionRequest.SerializeToString,
                response_deserializer=project3__pb2.AuctionUpdate.FromString,
                _registered_method=True)
        self.C_PlaceBid = channel.unary_unary(
                '/project3.ControllerService/C_PlaceBid',
                request_serializer=project3__pb2.PlaceBidRequest.SerializeToString,
                response_deserializer=project3__pb2.PlaceBidResponse.FromString,
                _registered_method=True)
        self.C_SendHeartbeat = channel.unary_unary(
                '/project3.ControllerService/C_SendHeartbeat',
                request_serializer=project3__pb2.Heartbeat.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def C_CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def C_GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def C_SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def C_UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def C_JoinAuction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def C_PlaceBid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def C_SendHeartbeat(self, request, context):
        """TODO: populate messages
        rpc C_CheckHealth(google.protobuf.Empty) returns (google.protobuf.Empty);
        (how callee sends a heartbeat message to the controller)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'C_CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.C_CreateItem,
                    request_deserializer=project3__pb2.CreateItemRequest.FromString,
                    response_serializer=project3__pb2.CreateItemResponse.SerializeToString,
            ),
            'C_GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.C_GetItem,
                    request_deserializer=project3__pb2.GetItemRequest.FromString,
                    response_serializer=project3__pb2.GetItemResponse.SerializeToString,
            ),
            'C_SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.C_SearchItems,
                    request_deserializer=project3__pb2.SearchItemsRequest.FromString,
                    response_serializer=project3__pb2.SearchItemsResponse.SerializeToString,
            ),
            'C_UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.C_UpdateItem,
                    request_deserializer=project3__pb2.UpdateItemRequest.FromString,
                    response_serializer=project3__pb2.UpdateItemResponse.SerializeToString,
            ),
            'C_JoinAuction': grpc.unary_stream_rpc_method_handler(
                    servicer.C_JoinAuction,
                    request_deserializer=project3__pb2.JoinAuctionRequest.FromString,
                    response_serializer=project3__pb2.AuctionUpdate.SerializeToString,
            ),
            'C_PlaceBid': grpc.unary_unary_rpc_method_handler(
                    servicer.C_PlaceBid,
                    request_deserializer=project3__pb2.PlaceBidRequest.FromString,
                    response_serializer=project3__pb2.PlaceBidResponse.SerializeToString,
            ),
            'C_SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.C_SendHeartbeat,
                    request_deserializer=project3__pb2.Heartbeat.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project3.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project3.ControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def C_CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ControllerService/C_CreateItem',
            project3__pb2.CreateItemRequest.SerializeToString,
            project3__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def C_GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ControllerService/C_GetItem',
            project3__pb2.GetItemRequest.SerializeToString,
            project3__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def C_SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ControllerService/C_SearchItems',
            project3__pb2.SearchItemsRequest.SerializeToString,
            project3__pb2.SearchItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def C_UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ControllerService/C_UpdateItem',
            project3__pb2.UpdateItemRequest.SerializeToString,
            project3__pb2.UpdateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def C_JoinAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/project3.ControllerService/C_JoinAuction',
            project3__pb2.JoinAuctionRequest.SerializeToString,
            project3__pb2.AuctionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def C_PlaceBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ControllerService/C_PlaceBid',
            project3__pb2.PlaceBidRequest.SerializeToString,
            project3__pb2.PlaceBidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def C_SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ControllerService/C_SendHeartbeat',
            project3__pb2.Heartbeat.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServiceNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.S_CreateItem = channel.unary_unary(
                '/project3.ServiceNodeService/S_CreateItem',
                request_serializer=project3__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.S_GetItem = channel.unary_unary(
                '/project3.ServiceNodeService/S_GetItem',
                request_serializer=project3__pb2.GetItemRequest.SerializeToString,
                response_deserializer=project3__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.S_SearchItems = channel.unary_unary(
                '/project3.ServiceNodeService/S_SearchItems',
                request_serializer=project3__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=project3__pb2.SearchItemsResponse.FromString,
                _registered_method=True)
        self.S_UpdateItem = channel.unary_unary(
                '/project3.ServiceNodeService/S_UpdateItem',
                request_serializer=project3__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.UpdateItemResponse.FromString,
                _registered_method=True)
        self.S_JoinAuction = channel.unary_stream(
                '/project3.ServiceNodeService/S_JoinAuction',
                request_serializer=project3__pb2.JoinAuctionRequest.SerializeToString,
                response_deserializer=project3__pb2.AuctionUpdate.FromString,
                _registered_method=True)
        self.S_PlaceBid = channel.unary_unary(
                '/project3.ServiceNodeService/S_PlaceBid',
                request_serializer=project3__pb2.PlaceBidRequest.SerializeToString,
                response_deserializer=project3__pb2.PlaceBidResponse.FromString,
                _registered_method=True)


class ServiceNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def S_CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S_GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S_SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S_UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S_JoinAuction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S_PlaceBid(self, request, context):
        """TODO: populate
        rpc S_HeartbeatRequest(google.protobuf.Empty) returns (Heartbeat);
        rpc S_Shutdown(google.protobuf.Empty) returns (google.protobuf.Empty); // for later: called by controller to shut down idle node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'S_CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.S_CreateItem,
                    request_deserializer=project3__pb2.CreateItemRequest.FromString,
                    response_serializer=project3__pb2.CreateItemResponse.SerializeToString,
            ),
            'S_GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.S_GetItem,
                    request_deserializer=project3__pb2.GetItemRequest.FromString,
                    response_serializer=project3__pb2.GetItemResponse.SerializeToString,
            ),
            'S_SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.S_SearchItems,
                    request_deserializer=project3__pb2.SearchItemsRequest.FromString,
                    response_serializer=project3__pb2.SearchItemsResponse.SerializeToString,
            ),
            'S_UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.S_UpdateItem,
                    request_deserializer=project3__pb2.UpdateItemRequest.FromString,
                    response_serializer=project3__pb2.UpdateItemResponse.SerializeToString,
            ),
            'S_JoinAuction': grpc.unary_stream_rpc_method_handler(
                    servicer.S_JoinAuction,
                    request_deserializer=project3__pb2.JoinAuctionRequest.FromString,
                    response_serializer=project3__pb2.AuctionUpdate.SerializeToString,
            ),
            'S_PlaceBid': grpc.unary_unary_rpc_method_handler(
                    servicer.S_PlaceBid,
                    request_deserializer=project3__pb2.PlaceBidRequest.FromString,
                    response_serializer=project3__pb2.PlaceBidResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project3.ServiceNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project3.ServiceNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def S_CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ServiceNodeService/S_CreateItem',
            project3__pb2.CreateItemRequest.SerializeToString,
            project3__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def S_GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ServiceNodeService/S_GetItem',
            project3__pb2.GetItemRequest.SerializeToString,
            project3__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def S_SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ServiceNodeService/S_SearchItems',
            project3__pb2.SearchItemsRequest.SerializeToString,
            project3__pb2.SearchItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def S_UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ServiceNodeService/S_UpdateItem',
            project3__pb2.UpdateItemRequest.SerializeToString,
            project3__pb2.UpdateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def S_JoinAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/project3.ServiceNodeService/S_JoinAuction',
            project3__pb2.JoinAuctionRequest.SerializeToString,
            project3__pb2.AuctionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def S_PlaceBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ServiceNodeService/S_PlaceBid',
            project3__pb2.PlaceBidRequest.SerializeToString,
            project3__pb2.PlaceBidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StorageServiceStub(object):
    """public api of storage nodes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/project3.StorageService/Put',
                request_serializer=project3__pb2.Item.SerializeToString,
                response_deserializer=project3__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/project3.StorageService/Get',
                request_serializer=project3__pb2.GetItemRequest.SerializeToString,
                response_deserializer=project3__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/project3.StorageService/Update',
                request_serializer=project3__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.UpdateItemResponse.FromString,
                _registered_method=True)
        self.HeartbeatRequest = channel.unary_unary(
                '/project3.StorageService/HeartbeatRequest',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=project3__pb2.Heartbeat.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """public api of storage nodes
    """

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=project3__pb2.Item.FromString,
                    response_serializer=project3__pb2.CreateItemResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=project3__pb2.GetItemRequest.FromString,
                    response_serializer=project3__pb2.GetItemResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=project3__pb2.UpdateItemRequest.FromString,
                    response_serializer=project3__pb2.UpdateItemResponse.SerializeToString,
            ),
            'HeartbeatRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatRequest,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=project3__pb2.Heartbeat.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project3.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project3.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """public api of storage nodes
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.StorageService/Put',
            project3__pb2.Item.SerializeToString,
            project3__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.StorageService/Get',
            project3__pb2.GetItemRequest.SerializeToString,
            project3__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.StorageService/Update',
            project3__pb2.UpdateItemRequest.SerializeToString,
            project3__pb2.UpdateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.StorageService/HeartbeatRequest',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            project3__pb2.Heartbeat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplicaNodeServiceStub(object):
    """api for storage nodes communicating amongst themselves
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.R_CreateItem = channel.unary_unary(
                '/project3.ReplicaNodeService/R_CreateItem',
                request_serializer=project3__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=project3__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.R_Read = channel.unary_unary(
                '/project3.ReplicaNodeService/R_Read',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.R_Write = channel.unary_unary(
                '/project3.ReplicaNodeService/R_Write',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=project3__pb2.Item.FromString,
                _registered_method=True)


class ReplicaNodeServiceServicer(object):
    """api for storage nodes communicating amongst themselves
    """

    def R_CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def R_Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def R_Write(self, request, context):
        """rpc R_HeartbeatRequest(google.protobuf.Empty) returns (Heartbeat);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'R_CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.R_CreateItem,
                    request_deserializer=project3__pb2.CreateItemRequest.FromString,
                    response_serializer=project3__pb2.CreateItemResponse.SerializeToString,
            ),
            'R_Read': grpc.unary_unary_rpc_method_handler(
                    servicer.R_Read,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'R_Write': grpc.unary_unary_rpc_method_handler(
                    servicer.R_Write,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=project3__pb2.Item.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project3.ReplicaNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project3.ReplicaNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicaNodeService(object):
    """api for storage nodes communicating amongst themselves
    """

    @staticmethod
    def R_CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ReplicaNodeService/R_CreateItem',
            project3__pb2.CreateItemRequest.SerializeToString,
            project3__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def R_Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ReplicaNodeService/R_Read',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def R_Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project3.ReplicaNodeService/R_Write',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            project3__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
