# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project3.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'project3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproject3.proto\x12\x08project3\x1a\x1bgoogle/protobuf/empty.proto\"\xd8\x01\n\x04Item\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x11\n\tseller_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x16\n\x0estarting_price\x18\x06 \x01(\x05\x12\x15\n\rcurrent_price\x18\x07 \x01(\x05\x12\x10\n\x08quantity\x18\x08 \x01(\x05\x12$\n\x06status\x18\t \x01(\x0e\x32\x14.project3.ItemStatus\x12\x0f\n\x07version\x18\n \x01(\t*=\n\nItemStatus\x12\x14\n\x10ITEM_STATUS_SOLD\x10\x00\x12\x19\n\x15ITEM_STATUS_AVAILABLE\x10\x01\x32\x84\x03\n\x11\x43ontrollerService\x12<\n\nCreateItem\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x39\n\x07GetItem\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12=\n\x0bSearchItems\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12<\n\nUpdateItem\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12=\n\x0bJoinAuction\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n\x08PlaceBid\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty2\x14\n\x12ServiceNodeService2\x14\n\x12StorageNodeServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMSTATUS']._serialized_start=276
  _globals['_ITEMSTATUS']._serialized_end=337
  _globals['_ITEM']._serialized_start=58
  _globals['_ITEM']._serialized_end=274
  _globals['_CONTROLLERSERVICE']._serialized_start=340
  _globals['_CONTROLLERSERVICE']._serialized_end=728
  _globals['_SERVICENODESERVICE']._serialized_start=730
  _globals['_SERVICENODESERVICE']._serialized_end=750
  _globals['_STORAGENODESERVICE']._serialized_start=752
  _globals['_STORAGENODESERVICE']._serialized_end=772
# @@protoc_insertion_point(module_scope)
